RELEASE_INTERVAL = 5 # seconds


FITNESSFORLIFE_USERNAME = "spociak.spot"
FITNESSFORLIFE_PASSWORD = "alberto123#!"

FITNESSTRZYKORONY_USERNAME = ""
FITNESSTRZYKORONY_PASSWORD = ""

HALNYGYM_USERNAME = ""
HALNYGYM_PASSWORD = ""

OXYGYM_USERNAME = ""
OXYGYM_PASSWORD = ""

XTREMEFITNESS_USERNAME = ""
XTREMEFITNESS_PASSWORD = ""