# Generated by Django 4.1.5 on 2023-01-15 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitnessforlife',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ip', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Fitnesstrzykorony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ip', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Halnygym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ip', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Oxygym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ip', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Xtremefitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_posted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_ip', models.GenericIPAddressField()),
                ('device', models.CharField(max_length=255)),
            ],
        ),
    ]
