# Generated by Django 4.1.5 on 2023-01-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymmaster', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitnesstrzykorony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('currTime', models.TimeField()),
                ('currDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Halnygym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('currTime', models.TimeField()),
                ('currDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Oxygym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('currTime', models.TimeField()),
                ('currDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Xtremefitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('currTime', models.TimeField()),
                ('currDate', models.DateField()),
            ],
        ),
    ]
